language: c

branches:
  only:
    - master

env:
  global:
    - GAPCONTAINER="gapsystem/gap-docker-stable-4.11"

  matrix:
    - PKG_NAME=agt
    - PKG_NAME=atlasrep
    - PKG_NAME=ctbllib
    - PKG_NAME=ferret
    - PKG_NAME=fr
    - PKG_NAME=gbnp
    - PKG_NAME=groupoids
    - PKG_NAME=hapcryst
    - PKG_NAME=hap
    - PKG_NAME=help # see https://github.com/gap-packages/HeLP/issues/3
    - PKG_NAME=openmath
    - PKG_NAME=packagemanager
    - PKG_NAME=polymaking
    - PKG_NAME=quagroup
    - PKG_NAME=rcwa
    - PKG_NAME=recog
    - PKG_NAME=semigroups
    - PKG_NAME=simpcomp
    - PKG_NAME=sla
    - PKG_NAME=sonata
    - PKG_NAME=xmod
    - PKG_NAME=yangbaxter

services:
  - docker

before_install:
  - docker version
  - docker pull ${GAPCONTAINER}

script:
  - docker run -v $PWD:/home/gap/travis/ ${GAPCONTAINER} /bin/sh -c "PKG_NAME=${PKG_NAME} TERM=xterm LANG=en_GB.UTF-8 /home/gap/travis/ci.sh"
