language: c

env:
  global:
    - GAPCONTAINER="gapsystem/gap-docker-stable-4.11"
    - GAPDIRNAME="gap-stable-4.11"

  matrix:
    - PKG_NAME=atlasrep
    - PKG_NAME=ctbllib
    - PKG_NAME=fr
    - PKG_NAME=gbnp
    - PKG_NAME=groupoids
    - PKG_NAME=hapcryst
    - PKG_NAME=intpic
    - PKG_NAME=packagemanager
    - PKG_NAME=polymaking
    - PKG_NAME=rcwa
    - PKG_NAME=recog
    - PKG_NAME=sla

services:
  - docker

before_install:
  - docker pull ${GAPCONTAINER}

script:
  - docker version
  - docker run -v $PWD:/home/gap/travis/ ${GAPCONTAINER} /bin/sh -c "GAPDIRNAME=${GAPDIRNAME} PKG_NAME=${PKG_NAME} TERM=xterm LANG=en_GB.UTF-8 /home/gap/travis/ci.sh"
